# Generated by Django 4.1.6 on 2023-04-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='boat_name',
        ),
    ]
