# Generated by Django 4.1.6 on 2023-05-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='ques',
            new_name='question',
        ),
    ]
